### PR TITLE
Feature/many many through list

### PR DESCRIPTION
**Pull request by fonsekaean**

### CODE REVIEW

**Comment by bummzack** [comment]
That looks like a good enhancement, thanks!
Any chance to get some unit-tests with this?

Also regarding your addition to documentation: Isn't that covered by this bit: https://github.com/bummzack/sortablefile#templates, or does something like `$Images.Sort('SortOrder')` not work with many-many-through?

**Comment by fonsekaean** [comment]
Thanks, and the doc change is needed as it needs to have that function for the upload field te render them in the correct order. 

Cheers

**Comment by fonsekaean** [comment]
I can send you unit tests too but you’d have to give me a couple of days to from some time :)

**Comment by bummzack** [comment]
Thanks for all your work on this! Strangely enough, the test-coverage still went down -22%. I'll have a look at it soon and maybe push to your branch, then merge.

**Comment by bummzack** [comment]
I've updated the code and readme and merged.
Thanks a lot for your contribution @fonsekaean , that's a great new feature to have! ❤️

**Comment by bummzack** [comment]
Released as `2.1`

**Pull request merged**
