### PR TITLE
MINOR: better getter in example

### PR DESCRIPTION
**Pull request by sunnysideup**
Awesome module!

### CODE REVIEW

**Review by bummzack — COMMENTED** [review]
Thanks for your addition. How is the `getManyManyComponents` better than using the "magic" accessor? 

I'd rather just keep one example to keep things terse.

**Comment by sunnysideup** [comment]
I don't really understand what you mean.

**Comment by bummzack** [comment]
Ah, I think I understand now. You're basically overriding the native accessor `Images` 🤔  
Have you used that in production? I've always been hesitant to override the native accessors, as it will make it harder to access the unmodified data-source

**Comment by sunnysideup** [comment]
We use this all the time in sortable gridfield: https://github.com/UndefinedOffset/SortableGridField/blob/master/docs/ManyManyExample.md... I totally agree and understand with your hesitation, but I can report that it seems to work most of the time.

**Comment by bummzack** [comment]
All good, thanks. I'll leave it up to the developer to decide

**Pull request merged**
