### PR TITLE
added code to handle has_many lists and updated the sort columns

### PR DESCRIPTION
**Pull request by fonsekaean**
This code updates files / images on a has many list, and directly writes the sort value on to the sort column

### CODE REVIEW

**Comment by bummzack** [comment]
Thanks for this! 
I deliberately removed `has_many` support. Is there a specific reason you added this back in?

There seems to be a linting error with the PHP code you added, see also: https://github.com/bummzack/sortablefile/blob/master/contributing.md#development-guidelines

Please also add unit-tests for the added functionality.

**Comment by fonsekaean** [comment]
Hello @bummzack 

Yes well there can be cases with extensions of the Image / File class which has a has_one to a certain object, like the case I've got. 

I will fix those lint issues. 

Thanks

**Comment by bummzack** [comment]
Why can't you use `many_many` in that instance though? See my reasoning why `has_many` was dropped: https://github.com/bummzack/sortablefile#what-happened-to-has_many-support

**Comment by fonsekaean** [comment]
Its a very specific reason I've got. We have an importer which imports listings which is a data object in the system, and has images for that. These images are very unlikely be shared across other objects. And the only bits a user would edit is the order of these items. 

But I see your point where when the image gets added on to a different object the first link will not be there anymore.

**Pull request closed without merging**
